load('//tests:test.bzl', 'test')

test('async_test.cc')

test('cookie_test.cc')
test('cookie_test_2.cc')
test('cookie_test_3.cc')

test('headers_test.cc')

test('http_client_test.cc')
test('http_parsing_test.cc')
test('http_server_test.cc')
test('http_uri_test.cc')

test('listener_test.cc')

test('mailbox_test.cc')

test('mime_test.cc')

test('net_test.cc')

test('payload_test.cc')

test('rest_server_test.cc')

test('router_test.cc')

test('streaming_test.cc')

test('string_view_test.cc')

test('typeid_test.cc')

test('view_test.cc')
